### PR TITLE
Added "interior" nodes, replaced FSanimateGeneric with ModuleAnimateG…

### PR DESCRIPTION
**Pull request by Kerbas-ad-astra**
…eneric, added ModuleCargoBay to bays, added DragCubes to cargo bays and hollow separators.

### CODE REVIEW

**Comment by Olympic1** [comment]
looks good.

Did you forgot to commit the DragCubes for the cargo bays or typed it wrong in the PR?

**Comment by Kerbas-ad-astra** [comment]
Oh yeah, they're on my testing install. Internet access for my dev machine is a bit infrequent at this time, but within a couple of days I'll have them up.

**Comment by taniwha** [comment]
Cool, I'll wait.

**Comment by Kerbas-ad-astra** [comment]
Cubes are in for the cargo bays.

**Comment by taniwha** [comment]
Thanks

**Pull request merged**
